project: KatanaUI

documentation:
  author: Bending Spoons Team
  author_url: http://bendingspoons.com
  github_url: https://github.com/BendingSpoons/katana-ui-swift

cocoapods:
  public_repo:
    email: opensource@bendingspoons.com
    author: Bending Spoons
  skip_linting: true  # Cannot lint because it depends on Katana, released always together

carthage:
  - KatanaUI
  - KatanaElements

tests:
  runs:
    - scheme: KatanaUI
      sdk: iphonesimulator11.2
      simulator: platform=iOS Simulator,OS=11.2,name=iPhone 7